apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-$DCK_IMAGE_SUFFIX-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-codeday
      role: $DCK_IMAGE_SUFFIX
  template:
    metadata:
      labels:
        app: nginx-codeday
        role: $DCK_IMAGE_SUFFIX
    spec:
      containers:
      - image: elyhamza/nginx-$DCK_IMAGE_SUFFIX:latest
        name: $DCK_IMAGE_SUFFIX
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"